In [71]:
# Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [72]:
#Importing Dataset
df = pd.read_csv('BankCustomers.csv')

In [73]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [74]:
X = df.iloc[:, 3:13]
y = df.iloc[:, 13]

In [75]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [76]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [77]:
#converging into dummy variables
state = pd.get_dummies(X['Geography'],drop_first=True)
gender = pd.get_dummies(X['Gender'],drop_first=True)

In [78]:
#concatenating dummy variables
X = pd.concat([X,state,gender],axis=1)

In [79]:
X = X.drop(['Geography','Gender'],axis=1)

In [80]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [81]:
#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [82]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [83]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform"))

# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=6, kernel_initializer="uniform"))

# Adding the output layer
classifier.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)

Epoch 1/100
700/700 [==============================] - 1s 445us/step - loss: 0.4931 - accuracy: 0.7967
Epoch 2/100
700/700 [==============================] - 0s 449us/step - loss: 0.4297 - accuracy: 0.7977
Epoch 3/100
700/700 [==============================] - 0s 446us/step - loss: 0.4248 - accuracy: 0.7977
Epoch 4/100
700/700 [==============================] - 0s 440us/step - loss: 0.4213 - accuracy: 0.7977
Epoch 5/100
700/700 [==============================] - 0s 438us/step - loss: 0.4180 - accuracy: 0.8207
Epoch 6/100
700/700 [==============================] - 0s 435us/step - loss: 0.4160 - accuracy: 0.8227
Epoch 7/100
700/700 [==============================] - 0s 442us/step - loss: 0.4145 - accuracy: 0.8280
Epoch 8/100
700/700 [==============================] - 0s 434us/step - loss: 0.4134 - accuracy: 0.8290
Epoch 9/100
700/700 [==============================] - 0s 444us/step - loss: 0.4120 - accuracy: 0.8301
Epoch 10/100
700/700 [==============================] - 0s 444us/step - loss: 0.4117 - accuracy: 0.8307
Epoch 11/100
700/700 [==============================] - 0s 461us/step - loss: 0.4104 - accuracy: 0.8307
Epoch 12/100
700/700 [==============================] - 0s 462us/step - loss: 0.4099 - accuracy: 0.8327
Epoch 13/100
700/700 [==============================] - 0s 451us/step - loss: 0.4091 - accuracy: 0.8340
Epoch 14/100
700/700 [==============================] - 0s 444us/step - loss: 0.4090 - accuracy: 0.8330
Epoch 15/100
700/700 [==============================] - 0s 454us/step - loss: 0.4080 - accuracy: 0.8351
Epoch 16/100
700/700 [==============================] - 0s 442us/step - loss: 0.4074 - accuracy: 0.8331
Epoch 17/100
700/700 [==============================] - 0s 438us/step - loss: 0.4071 - accuracy: 0.8349
Epoch 18/100
700/700 [==============================] - 0s 450us/step - loss: 0.4068 - accuracy: 0.8334
Epoch 19/100
700/700 [==============================] - 0s 445us/step - loss: 0.4062 - accuracy: 0.8330
Epoch 20/100
700/700 [==============================] - 0s 444us/step - loss: 0.4057 - accuracy: 0.8337
Epoch 21/100
700/700 [==============================] - 0s 460us/step - loss: 0.4056 - accuracy: 0.8331
Epoch 22/100
700/700 [==============================] - 0s 451us/step - loss: 0.4047 - accuracy: 0.8347
Epoch 23/100
700/700 [==============================] - 0s 449us/step - loss: 0.4044 - accuracy: 0.8337
Epoch 24/100
700/700 [==============================] - 0s 445us/step - loss: 0.4030 - accuracy: 0.8353
Epoch 25/100
700/700 [==============================] - 0s 443us/step - loss: 0.4020 - accuracy: 0.8341
Epoch 26/100
700/700 [==============================] - 0s 440us/step - loss: 0.4015 - accuracy: 0.8346
Epoch 27/100
700/700 [==============================] - 0s 542us/step - loss: 0.4007 - accuracy: 0.8364
Epoch 28/100
700/700 [==============================] - 0s 696us/step - loss: 0.4002 - accuracy: 0.8350
Epoch 29/100
700/700 [==============================] - 0s 703us/step - loss: 0.3989 - accuracy: 0.8331
Epoch 30/100
700/700 [==============================] - 1s 750us/step - loss: 0.3993 - accuracy: 0.8331
Epoch 31/100
700/700 [==============================] - 1s 856us/step - loss: 0.3988 - accuracy: 0.8343
Epoch 32/100
700/700 [==============================] - 0s 461us/step - loss: 0.3985 - accuracy: 0.8341
Epoch 33/100
700/700 [==============================] - 0s 465us/step - loss: 0.3980 - accuracy: 0.8346
Epoch 34/100
700/700 [==============================] - 0s 542us/step - loss: 0.3978 - accuracy: 0.8344
Epoch 35/100
700/700 [==============================] - 0s 673us/step - loss: 0.3972 - accuracy: 0.8343
Epoch 36/100
700/700 [==============================] - 0s 466us/step - loss: 0.3966 - accuracy: 0.8351
Epoch 37/100
700/700 [==============================] - 0s 454us/step - loss: 0.3961 - accuracy: 0.8351
Epoch 38/100
700/700 [==============================] - 0s 452us/step - loss: 0.3969 - accuracy: 0.8359
Epoch 39/100
700/700 [==============================] - 0s 460us/step - loss: 0.3961 - accuracy: 0.8359
Epoch 40/100
700/700 [==============================] - 0s 469us/step - loss: 0.3960 - accuracy: 0.8344
Epoch 41/100
700/700 [==============================] - 0s 452us/step - loss: 0.3956 - accuracy: 0.8366
Epoch 42/100
700/700 [==============================] - 0s 457us/step - loss: 0.3954 - accuracy: 0.8361
Epoch 43/100
700/700 [==============================] - 0s 447us/step - loss: 0.3947 - accuracy: 0.8356
Epoch 44/100
700/700 [==============================] - 0s 467us/step - loss: 0.3952 - accuracy: 0.8354
Epoch 45/100
700/700 [==============================] - 0s 461us/step - loss: 0.3948 - accuracy: 0.8353
Epoch 46/100
700/700 [==============================] - 0s 467us/step - loss: 0.3944 - accuracy: 0.8350
Epoch 47/100
700/700 [==============================] - 0s 464us/step - loss: 0.3953 - accuracy: 0.8354
Epoch 48/100
700/700 [==============================] - 0s 462us/step - loss: 0.3948 - accuracy: 0.8366
Epoch 49/100
700/700 [==============================] - 0s 464us/step - loss: 0.3946 - accuracy: 0.8366
Epoch 50/100
700/700 [==============================] - 0s 497us/step - loss: 0.3952 - accuracy: 0.8356
Epoch 51/100
700/700 [==============================] - 0s 452us/step - loss: 0.3940 - accuracy: 0.8360
Epoch 52/100
700/700 [==============================] - 0s 471us/step - loss: 0.3939 - accuracy: 0.8370
Epoch 53/100
700/700 [==============================] - 0s 448us/step - loss: 0.3947 - accuracy: 0.8359
Epoch 54/100
700/700 [==============================] - 0s 437us/step - loss: 0.3941 - accuracy: 0.8376
Epoch 55/100
700/700 [==============================] - 0s 434us/step - loss: 0.3940 - accuracy: 0.8359
Epoch 56/100
700/700 [==============================] - 0s 428us/step - loss: 0.3941 - accuracy: 0.8363
Epoch 57/100
700/700 [==============================] - 0s 427us/step - loss: 0.3944 - accuracy: 0.8370
Epoch 58/100
700/700 [==============================] - 0s 440us/step - loss: 0.3937 - accuracy: 0.8371
Epoch 59/100
700/700 [==============================] - 0s 429us/step - loss: 0.3938 - accuracy: 0.8366
Epoch 60/100
700/700 [==============================] - 0s 436us/step - loss: 0.3941 - accuracy: 0.8363
Epoch 61/100
700/700 [==============================] - 0s 428us/step - loss: 0.3927 - accuracy: 0.8376
Epoch 62/100
700/700 [==============================] - 0s 429us/step - loss: 0.3934 - accuracy: 0.8386
Epoch 63/100
700/700 [==============================] - 0s 422us/step - loss: 0.3940 - accuracy: 0.8370
Epoch 64/100
700/700 [==============================] - 0s 442us/step - loss: 0.3935 - accuracy: 0.8369
Epoch 65/100
700/700 [==============================] - 0s 426us/step - loss: 0.3929 - accuracy: 0.8376
Epoch 66/100
700/700 [==============================] - 0s 430us/step - loss: 0.3932 - accuracy: 0.8381
Epoch 67/100
700/700 [==============================] - 0s 426us/step - loss: 0.3936 - accuracy: 0.8353
Epoch 68/100
700/700 [==============================] - 0s 576us/step - loss: 0.3931 - accuracy: 0.8373
Epoch 69/100
700/700 [==============================] - 0s 437us/step - loss: 0.3929 - accuracy: 0.8376
Epoch 70/100
700/700 [==============================] - 0s 443us/step - loss: 0.3929 - accuracy: 0.8373
Epoch 71/100
700/700 [==============================] - 0s 432us/step - loss: 0.3928 - accuracy: 0.8367
Epoch 72/100
700/700 [==============================] - 0s 426us/step - loss: 0.3925 - accuracy: 0.8356
Epoch 73/100
700/700 [==============================] - 0s 435us/step - loss: 0.3931 - accuracy: 0.8360
Epoch 74/100
700/700 [==============================] - 0s 520us/step - loss: 0.3927 - accuracy: 0.8359
Epoch 75/100
700/700 [==============================] - 0s 459us/step - loss: 0.3930 - accuracy: 0.8349
Epoch 76/100
700/700 [==============================] - 0s 517us/step - loss: 0.3928 - accuracy: 0.8353
Epoch 77/100
700/700 [==============================] - 0s 534us/step - loss: 0.3925 - accuracy: 0.8366
Epoch 78/100
700/700 [==============================] - 0s 488us/step - loss: 0.3928 - accuracy: 0.8369
Epoch 79/100

700/700 [==============================] - 0s 480us/step - loss: 0.3924 - accuracy: 0.8369
Epoch 80/100
700/700 [==============================] - 0s 481us/step - loss: 0.3925 - accuracy: 0.8366
Epoch 81/100
700/700 [==============================] - 0s 603us/step - loss: 0.3925 - accuracy: 0.8374
Epoch 82/100
700/700 [==============================] - 0s 565us/step - loss: 0.3924 - accuracy: 0.8361
Epoch 83/100
700/700 [==============================] - 1s 762us/step - loss: 0.3926 - accuracy: 0.8380
Epoch 84/100
700/700 [==============================] - 0s 426us/step - loss: 0.3923 - accuracy: 0.8346
Epoch 85/100
700/700 [==============================] - 0s 430us/step - loss: 0.3926 - accuracy: 0.8370
Epoch 86/100
700/700 [==============================] - 0s 434us/step - loss: 0.3921 - accuracy: 0.8381
Epoch 87/100
700/700 [==============================] - 0s 428us/step - loss: 0.3920 - accuracy: 0.8381
Epoch 88/100
700/700 [==============================] - 0s 514us/step - loss: 0.3918 - accuracy: 0.8390
Epoch 89/100
700/700 [==============================] - 0s 521us/step - loss: 0.3918 - accuracy: 0.8413
Epoch 90/100
700/700 [==============================] - 0s 551us/step - loss: 0.3913 - accuracy: 0.8389
Epoch 91/100
700/700 [==============================] - 0s 567us/step - loss: 0.3904 - accuracy: 0.8399
Epoch 92/100
700/700 [==============================] - 0s 548us/step - loss: 0.3884 - accuracy: 0.8409
Epoch 93/100
700/700 [==============================] - 0s 583us/step - loss: 0.3849 - accuracy: 0.8420
Epoch 94/100
700/700 [==============================] - 0s 479us/step - loss: 0.3775 - accuracy: 0.8427
Epoch 95/100
700/700 [==============================] - 0s 501us/step - loss: 0.3714 - accuracy: 0.84690s - loss: 0.3724 - accuracy: 0.84
Epoch 96/100
700/700 [==============================] - 0s 572us/step - loss: 0.3678 - accuracy: 0.8466
Epoch 97/100
700/700 [==============================] - 0s 555us/step - loss: 0.3636 - accuracy: 0.8489
Epoch 98/100
700/700 [==============================] - 0s 553us/step - loss: 0.3603 - accuracy: 0.8517
Epoch 99/100
700/700 [==============================] - 0s 516us/step - loss: 0.3586 - accuracy: 0.8526
Epoch 100/100
700/700 [==============================] - 0s 524us/step - loss: 0.3579 - accuracy: 0.8537

In [84]:
#predicting Test set results 
y_pred = classifier.predict(X_test)

In [85]:
y_pred

array([[0.23246303],
       [0.33678138],
       [0.17383626],
       ...,
       [0.17513144],
       [0.09448397],
       [0.5226925 ]], dtype=float32)

In [86]:
y_pred = (y_pred>0.5)

In [87]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [88]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

In [89]:
cm

array([[2270,  109],
       [ 332,  289]], dtype=int64)

In [90]:
accuracy

0.853